global.SUCCESS_REQUEST=200;
global.NO_CONTENT_CODE=204;
global.BAD_REQUEST=400;
global.CREATED_CODE=201;
global.UN_AUTH_CODE=401;
global.NOT_ACCEPTABLE=406;
global.CONFLICT_CODE=409,

global.DATABASE_NAME = 'Demo';
global.DATABASE_USERNAME = 'smt';
global.DATABASE_PASSWORD = 'abc123';
global.DATABASE_HOST = 'localhost';
